#!/usr/bin/env python3
"""BLACK outbound worker. Standard library only; no arbitrary shell jobs."""
import base64, datetime, fcntl, hashlib, html, json, os, pathlib, re, sys, time
import urllib.error, urllib.request
REPO = "amillimatrix-eng/CARBON-Creation-Hub"
ROOT = pathlib.Path(os.environ.get("BLACK_HOME", str(pathlib.Path.home() / ".local/share/amx-black")))
ROOT.mkdir(parents=True, exist_ok=True)
def now():
    return datetime.datetime.now(datetime.timezone.utc).isoformat()
def api(method, path, data=None):
    token = (ROOT / "token").read_text().strip()
    url = "https://api.github.com/repos/" + REPO + "/contents/" + path
    req = urllib.request.Request(url, data=None if data is None else json.dumps(data).encode(),
        method=method, headers={"Authorization": "Bearer " + token,
        "Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "AMX-BLACK/1"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r)
    except urllib.error.HTTPError as e:
        if e.code == 404 and method == "GET":
            return None
        raise RuntimeError("GitHub HTTP " + str(e.code)) from None
def read(path):
    obj = api("GET", path)
    if obj is None:
        return None, None
    return base64.b64decode(obj["content"]), obj["sha"]
def write(path, value, expected=None):
    body = {"message": "BLACK: " + path, "content": base64.b64encode(value).decode()}
    if expected:
        body["sha"] = expected
    return api("PUT", path, body)
def put_json(path, obj, sha=None):
    return write(path, (json.dumps(obj, indent=2, sort_keys=True) + "\n").encode(), sha)
def manifest():
    # Only already-public fixed package paths can be read or returned by this adapter.
    paths = ("README.md", "RIGHTS.md", "releases/production001.json", "assets/production001-poster.svg")
    files = []
    for p in paths:
        data, blob = read(p)
        if data is None:
            raise RuntimeError("Required public package file missing")
        files.append({"path": p, "git_blob": blob, "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)})
    return {"title": "CARBON° — Degree of Business", "generated_at": now(),
        "files": files, "scope": "Public package record integrity only",
        "video_access": "UNVERIFIED", "external_acceptance": "UNVERIFIED", "payment": "UNVERIFIED"}
def execute(job):
    jid = job.get("id", "")
    if not re.fullmatch(r"[A-Za-z0-9_-]{1,80}", jid):
        raise RuntimeError("Invalid task ID")
    if job.get("worker") != "BLACK" or job.get("adapter") != "package_manifest":
        raise RuntimeError("Unsupported task assignment or adapter")
    task_hash = hashlib.sha256(json.dumps(job, sort_keys=True).encode()).hexdigest()
    receipt_path = "black-control/receipts/" + jid + ".json"
    old, receipt_sha = read(receipt_path)
    if old:
        previous = json.loads(old)
        if previous.get("task_sha256") != task_hash:
            raise RuntimeError("Task ID reused with different instructions")
        if previous.get("status") in ("DONE", "FAILED"):
            return
    started = now()
    claim = {"task_id": jid, "worker": "BLACK", "task_sha256": task_hash,
        "status": "RUNNING", "started_at": started}
    # Compare-and-swap/create prevents competing claims. Single enrolled BLACK only.
    result = put_json(receipt_path, claim, receipt_sha)
    receipt_sha = result["content"]["sha"]
    try:
        output = manifest()
        artifact = (json.dumps(output, indent=2, sort_keys=True) + "\n").encode()
        artifact_path = "black-control/artifacts/" + jid + ".json"
        prior, blob = read(artifact_path)
        write(artifact_path, artifact, blob)
        page = ("<!doctype html><html lang=en><meta charset=utf-8>"
            "<meta name=viewport content='width=device-width,initial-scale=1'>"
            "<title>CARBON° package manifest</title>"
            "<style>body{background:#171717;color:#eee;font:16px system-ui;margin:2rem;max-width:70rem}"
            "pre{white-space:pre-wrap;overflow-wrap:anywhere}h1{font-size:1.6rem}</style>"
            "<h1>CARBON° — Package manifest</h1><p>Generated by BLACK. "
            "Package integrity evidence; video access and commercial outcomes remain unverified.</p>"
            "<pre>" + html.escape(artifact.decode()) + "</pre></html>").encode()
        page_path = "black-control/artifacts/" + jid + ".html"
        prior, blob = read(page_path)
        write(page_path, page, blob)
        claim.update(status="DONE", completed_at=now(), artifact=artifact_path,
            artifact_sha256=hashlib.sha256(artifact).hexdigest(), html_artifact=page_path)
    except Exception as e:
        claim.update(status="FAILED", completed_at=now(), error_type=type(e).__name__)
    put_json(receipt_path, claim, receipt_sha)
def cycle():
    raw, _ = read("black-control/queue.json")
    if raw is None:
        raise RuntimeError("Queue missing")
    queue = json.loads(raw)
    if queue.get("schema") != 1 or len(queue.get("jobs", [])) > 100:
        raise RuntimeError("Unsupported queue")
    for job in queue.get("jobs", []):
        if job.get("worker") == "BLACK":
            execute(job)
def main():
    lock = (ROOT / "worker.lock").open("a")
    try:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        return
    while True:
        try:
            cycle()
            (ROOT / "last-cycle.json").write_text(json.dumps({"at": now(), "status": "OK"}))
            if "--once" in sys.argv:
                return
            time.sleep(60)
        except Exception as e:
            # Never log tokens, URLs carrying credentials, host identity or private files.
            print("BLACK cycle failed: " + type(e).__name__, flush=True)
            if "--once" in sys.argv:
                raise SystemExit(1)
            time.sleep(120)
if __name__ == "__main__":
    main()
