(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const P={browser:{label:"Browser",actor:"carbon-demo-browser-2026"},buyer:{label:"Buyer",actor:"carbon-demo-buyer-2026"},seller:{label:"Seller",actor:"carbon-demo-seller-2026"}};
const S={persona:"browser",filter:"ALL",listings:[],me:null,activeListing:null,activeInterest:null,activeCommitment:null,interestRecords:[],interestListing:null};
const money=(n,c="ZAR")=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:c,maximumFractionDigits:0}).format((n||0)/100);

function toast(message,bad=false){const el=$("#toast");el.textContent=message;el.classList.toggle("bad",bad);el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
async function api(path,opt={}){const options={...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}};if(opt.actor!==false)options.headers["X-CARBON-Actor"]=P[S.persona].actor;const response=await fetch(path,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||("Request failed "+response.status));return data}
function esc(value=""){const d=document.createElement("div");d.textContent=value;return d.innerHTML}
function setView(name){$$(".view").forEach(x=>x.classList.toggle("activeView",x.id===name));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===name));if(name==="sell")renderSeller();if(name==="activity")renderActivity()}
async function cyclePersona(){const order=["browser","buyer","seller"];S.persona=order[(order.indexOf(S.persona)+1)%3];$("#personaLabel").textContent=P[S.persona].label;await refresh();toast("Now acting as "+P[S.persona].label);if(S.persona==="seller")setView("sell")}
function intentScore(x){const posture={PATIENT:1,OPEN:2,MOTIVATED:3,URGENT:4}[x.seller_intent]||1;return posture*10+x.market.bonded*2+x.market.qualified*3+x.market.active_commitments*5}
function visibleListings(){let list=S.listings.filter(x=>S.filter==="ALL"||x.seller_intent===S.filter);if(Number($("#intent").value)>=60)list=[...list].sort((a,b)=>intentScore(b)-intentScore(a));return list}
function render(){renderMarket();renderSeller();renderActivity()}
function evidenceText(e,label){if(!e||e.evidence_state==="UNKNOWN")return label+" evidence: unknown — not bad.";return label+" evidence: "+e.honoured+" honoured · "+e.bonded_deals+" bonded deals · "+e.valid_exits+" valid exits · "+e.review_states+" review states."}
function renderMarket(){const list=visibleListings();$("#emptyMarket").classList.toggle("hidden",list.length>0);$("#grid").innerHTML=list.map(card).join("");const totals=S.listings.reduce((a,x)=>{a.bonded+=x.market.bonded;a.qualified+=x.market.qualified;a.active+=x.market.active_commitments;return a},{bonded:0,qualified:0,active:0});$("#stats").innerHTML='<span class="stat"><b>'+S.listings.length+'</b> listings</span><span class="stat"><b>'+totals.bonded+'</b> bonded</span><span class="stat"><b>'+totals.qualified+'</b> qualified</span><span class="stat"><b>'+totals.active+'</b> active</span>';$$("[data-bond]").forEach(b=>b.onclick=()=>openBond(b.dataset.bond));$$("[data-interest]").forEach(b=>b.onclick=()=>openInterests(b.dataset.interest))}
function card(x){const mine=Boolean(S.me&&S.me.actor_ref===x.seller_ref);let action='<button class="button primary" data-bond="'+x.id+'">Show intent</button>';if(S.persona==="seller"&&mine)action='<button class="button" data-interest="'+x.id+'">Qualified interest</button>';if(S.persona==="seller"&&!mine)action='<span class="pill">Another seller\'s listing</span>';return '<article class="card"><div class="cardTop"><span class="state">'+x.seller_intent+'</span><span class="muted">'+x.negotiability+'</span></div><h3>'+esc(x.title)+'</h3><div class="price">'+money(x.price_minor,x.currency)+'</div><p>'+esc(x.description||"")+'</p><p class="muted">Minimum bond '+money(x.min_bond_minor,x.currency)+' · maximum meaningful commitment '+money(x.max_considered_bond_minor,x.currency)+'.</p><p class="muted">'+esc(evidenceText(x.seller_evidence,"Seller"))+'</p><div class="signals"><div class="signal"><b>'+x.market.bonded+'</b><span>bonded</span></div><div class="signal"><b>'+x.market.qualified+'</b><span>qualified</span></div><div class="signal"><b>'+x.market.active_commitments+'</b><span>active</span></div></div><div class="actions">'+action+'</div></article>'}
function renderSeller(){const el=$("#sellerListings");if(S.persona!=="seller"){el.innerHTML='<div class="empty"><b>Seller controls stay with the seller.</b><span>Switch to Seller to publish or select.</span></div>';return}const owned=(S.me&&S.me.listings)||[];el.innerHTML=owned.length?owned.map(raw=>{const x=S.listings.find(l=>l.id===raw.id)||raw;const market=x.market||{bonded:0,qualified:0};return '<div class="row"><div class="rowMain"><strong>'+esc(x.title)+'</strong><span>'+x.seller_intent+' · '+money(x.min_bond_minor,x.currency)+' minimum · '+market.bonded+' bonded</span></div><button class="button" data-interest="'+x.id+'">Review</button></div>'}).join(""):'<div class="empty"><b>No seller listings yet.</b><span>Publish only when you actually want to sell.</span></div>';$$("[data-interest]",el).forEach(b=>b.onclick=()=>openInterests(b.dataset.interest))}
function activityRows(){if(!S.me)return[];const rows=[];(S.me.interests||[]).forEach(r=>rows.push({kind:"interest",record:r,updated:r.updated_at}));(S.me.commitments||[]).forEach(r=>rows.push({kind:"commitment",record:r,updated:r.updated_at}));(S.me.deals||[]).forEach(r=>rows.push({kind:"deal",record:r,updated:r.updated_at}));(S.me.extensions||[]).forEach(r=>rows.push({kind:"extension",record:r,updated:r.updated_at}));return rows.sort((a,b)=>String(b.updated).localeCompare(String(a.updated)))}
function activityButtons(item){const r=item.record,me=S.me&&S.me.actor_ref;if(item.kind==="commitment"){if(r.state==="SELECTED"&&r.buyer_ref===me)return '<button class="button primary" data-action="confirm" data-id="'+r.id+'">Confirm</button><button class="button" data-action="cancel" data-id="'+r.id+'">Exit</button>';if(r.state==="SELECTED"&&r.seller_ref===me)return '<button class="button" data-action="cancel" data-id="'+r.id+'">Release</button>';if(r.state==="ACTIVE_COMMITMENT"){const already=(r.buyer_ref===me&&r.buyer_performed)||(r.seller_ref===me&&r.seller_performed);return (already?'<span class="pill">Performance recorded</span>':'<button class="button primary" data-action="perform" data-id="'+r.id+'">Confirm performance</button>')+'<button class="button" data-action="extend" data-id="'+r.id+'">Extend</button><button class="button" data-action="cancel" data-id="'+r.id+'">Exit</button>'}if(r.state==="HONOURED")return '<button class="button primary" data-action="deal" data-id="'+r.id+'">Inspect / deal</button>'}if(item.kind==="extension"&&r.status==="PENDING"){const com=(S.me&&S.me.commitments||[]).find(x=>x.id===r.commitment_id);if(com&&r.requester_ref!==me)return '<button class="button primary" data-action="extension-accept" data-id="'+r.id+'">Accept change</button><button class="button" data-action="extension-reject" data-id="'+r.id+'">Reject</button>';return '<span class="pill">Waiting for response</span>'}if(item.kind==="deal"&&r.state==="INSPECTION"){const accepted=(r.buyer_ref===me&&r.buyer_accept)||(r.seller_ref===me&&r.seller_accept);return (accepted?'<span class="pill">Your acceptance recorded</span>':'<button class="button primary" data-action="accept" data-id="'+r.id+'">Accept deal</button>')+'<button class="button" data-action="decline" data-id="'+r.id+'">No deal</button>'}return ""}
function activityNote(item){const r=item.record;if(item.kind==="interest"){if(r.state==="BONDED_INTEREST")return "Waiting for seller selection. No breach consequence is active.";if(r.state.includes("RELEASE"))return "Liquidity is marked for release.";return "Buyer intent evidence."}if(item.kind==="commitment"){if(r.state==="SELECTED")return "Seller selected. Buyer must confirm before consequence activates.";if(r.state==="ACTIVE_COMMITMENT")return "Bilateral commitment is active until "+new Date(r.end_at).toLocaleString()+".";if(r.state==="PERFORMANCE_REVIEW")return "Time window ended. CARBON° did not infer who was at fault.";if(r.state==="HONOURED")return "Both parties confirmed performance.";return r.resolution||"Commitment evidence."}if(item.kind==="extension"){if(r.status==="PENDING")return "Requested change. Original commitment remains in force until accepted.";if(r.status==="ACCEPTED")return "Both parties accepted the new time window.";return "Extension was not accepted; original commitment remained in force."}if(item.kind==="deal"){if(r.state==="INSPECTION")return "Inspection stage. Both sides retain their own acceptance decision.";if(r.state==="BONDED_DEAL")return "Both accepted. Settlement is ready for a regulated provider.";if(r.state==="NO_DEAL")return "Inspection ended without a purchase. The honoured commitment can release.";return r.settlement_state||"Deal evidence."}return ""}
function messageInterestId(item){if(item.kind==="interest")return item.record.id;if(item.kind==="commitment")return item.record.interest_id;if(item.kind==="extension"){const c=(S.me&&S.me.commitments||[]).find(x=>x.id===item.record.commitment_id);return c&&c.interest_id}if(item.kind==="deal"){const c=(S.me&&S.me.commitments||[]).find(x=>x.id===item.record.commitment_id);return c&&c.interest_id}return null}
function renderActivity(){const rows=activityRows(),el=$("#activityList");$("#emptyActivity").classList.toggle("hidden",rows.length>0);el.innerHTML=rows.map(item=>{const r=item.record,id=messageInterestId(item);const msg=id?'<button class="button" data-message="'+id+'">Message</button>':"";return '<div class="row"><div class="rowMain"><span class="state">'+esc(r.state||item.kind)+'</span><strong>'+esc(r.id)+'</strong><span>'+esc(activityNote(item))+'</span></div><div class="actions">'+msg+activityButtons(item)+'</div></div>'}).join("");$("[data-action]",el).forEach(b=>b.onclick=()=>activityAction(b.dataset.action,b.dataset.id));$("[data-message]",el).forEach(b=>b.onclick=()=>openMessages(b.dataset.message))}
async function activityAction(action,id){try{let out;if(action==="confirm")out=await api("/api/carbon/commitments/"+id+"/confirm",{method:"POST"});if(action==="perform")out=await api("/api/carbon/commitments/"+id+"/perform",{method:"POST"});if(action==="deal")out=await api("/api/carbon/commitments/"+id+"/deal",{method:"POST"});if(action==="accept")out=await api("/api/carbon/deals/"+id+"/accept",{method:"POST"});if(action==="extend"){openExtension(id);return}if(action==="extension-accept")out=await api("/api/carbon/extensions/"+id+"/respond",{method:"POST",body:JSON.stringify({action:"ACCEPT"})});if(action==="extension-reject")out=await api("/api/carbon/extensions/"+id+"/respond",{method:"POST",body:JSON.stringify({action:"REJECT"})});if(action==="decline"){const reason=prompt("Why is there no deal? (optional):","")||"";out=await api("/api/carbon/deals/"+id+"/decline",{method:"POST",body:JSON.stringify({reason})})}if(action==="cancel"){const reason=prompt("Reason for exit (optional):","")||"";out=await api("/api/carbon/commitments/"+id+"/cancel",{method:"POST",body:JSON.stringify({reason})})}if(!out)return;toast("State recorded.");await refresh()}catch(e){toast(e.message,true)}}
function openBond(id){if(S.persona==="browser"){S.persona="buyer";$("#personaLabel").textContent=P.buyer.label}if(S.persona!=="buyer"){toast("Switch to Buyer first.",true);return}const x=S.listings.find(y=>y.id===id);if(!x)return;if(S.me&&S.me.actor_ref===x.seller_ref){toast("You cannot bond your own listing.",true);return}S.activeListing=x;$("#bondTitle").textContent=x.title;$("#bondRules").textContent="Seller requires at least "+money(x.min_bond_minor,x.currency)+". CARBON° will not accept more than "+money(x.max_considered_bond_minor,x.currency)+" for this commitment.";const amount=$("#bondAmount");amount.min=Math.max(1,Math.round(x.min_bond_minor/100));amount.max=Math.max(Number(amount.min),Math.round(x.max_considered_bond_minor/100));amount.value=amount.min;const risk=$("#riskAmount");risk.min=Math.round(x.min_at_risk_bps/100);risk.max=Math.round(x.max_at_risk_bps/100);risk.value=risk.min;const d=new Date(Date.now()+90*60000);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$("#meeting").value=d.toISOString().slice(0,16);syncBond();$("#bondDialog").showModal()}
function syncBond(){$("#bondOut").textContent="R"+Number($("#bondAmount").value).toLocaleString("en-ZA");$("#riskOut").textContent=$("#riskAmount").value+"%"}
async function submitBond(e){e.preventDefault();const x=S.activeListing;if(!x)return;try{const local=new Date($("#meeting").value);await api("/api/carbon/listings/"+x.id+"/interests",{method:"POST",body:JSON.stringify({bond_minor:Math.round(Number($("#bondAmount").value)*100),at_risk_bps:Math.round(Number($("#riskAmount").value)*100),proposed_start_at:local.toISOString(),proposed_duration_minutes:Number($("#duration").value)})});$("#bondDialog").close();toast("Intent secured. No priority purchased.");await refresh();setView("activity")}catch(err){toast(err.message,true)}}
function renderInterestCandidates(){const x=S.interestListing;if(!x)return;const minBond=Number($("#interestBondFilter").value)*100,minRisk=Number($("#interestRiskFilter").value)*100,today=$("#interestTodayFilter").checked;$("#interestBondOut").textContent="R"+Number($("#interestBondFilter").value).toLocaleString("en-ZA");$("#interestRiskOut").textContent=$("#interestRiskFilter").value+"%";const now=new Date();const records=S.interestRecords.filter(i=>i.considered_bond_minor>=minBond&&i.at_risk_bps>=minRisk&&(!today||new Date(i.proposed_start_at).toDateString()===now.toDateString()));$("#interestList").innerHTML=records.length?records.map(i=>'<div class="row"><div class="rowMain"><span class="state">'+i.state+'</span><strong>'+money(i.considered_bond_minor,x.currency)+' committed</strong><span>'+Math.round(i.at_risk_bps/100)+'% proposed at risk · '+new Date(i.proposed_start_at).toLocaleString()+'</span><span>'+esc(evidenceText(i.buyer_evidence,"Buyer"))+'</span></div><div class="actions"><button class="button" data-message="'+i.id+'">Message</button>'+(i.state==="BONDED_INTEREST"?'<button class="button primary" data-select="'+i.id+'">Select</button>':'')+'</div></div>').join(""):'<div class="empty"><b>No buyers match these filters.</b><span>Move the sliders; nobody is penalized for falling outside your current view.</span></div>';$("[data-select]",$("#interestList")).forEach(b=>b.onclick=()=>selectInterest(b.dataset.select));$("[data-message]",$("#interestList")).forEach(b=>b.onclick=()=>openMessages(b.dataset.message))}
async function openInterests(id){if(S.persona!=="seller"){toast("Seller credential required.",true);return}const x=S.listings.find(y=>y.id===id);if(!x||!S.me||S.me.actor_ref!==x.seller_ref){toast("Only this listing's seller can review qualified interest.",true);return}try{const data=await api("/api/carbon/listings/"+id+"/interests");S.interestRecords=data.records;S.interestListing=x;$("#interestTitle").textContent=x.title;const b=$("#interestBondFilter"),r=$("#interestRiskFilter");b.min=Math.round(x.min_bond_minor/100);b.max=Math.round(x.max_considered_bond_minor/100);b.value=b.min;r.min=Math.round(x.min_at_risk_bps/100);r.max=Math.round(x.max_at_risk_bps/100);r.value=r.min;$("#interestTodayFilter").checked=false;renderInterestCandidates();$("#interestDialog").showModal()}catch(err){toast(err.message,true)}}
async function selectInterest(id){try{await api("/api/carbon/interests/"+id+"/select",{method:"POST",body:JSON.stringify({cancellation_buffer_minutes:120})});$("#interestDialog").close();toast("Selected. Buyer consequence remains inactive.");await refresh();setView("activity")}catch(err){toast(err.message,true)}}
async function createListing(e){e.preventDefault();if(S.persona!=="seller"){toast("Switch to Seller first.",true);return}const f=new FormData(e.currentTarget);try{await api("/api/carbon/listings",{method:"POST",body:JSON.stringify({title:f.get("title"),description:f.get("description"),price_minor:Math.round(Number(f.get("price"))*100),currency:"ZAR",seller_intent:f.get("seller_intent"),negotiability:f.get("negotiability"),min_bond_minor:Math.round(Number(f.get("min_bond"))*100),max_considered_bond_minor:Math.round(Number(f.get("max_bond"))*100),min_at_risk_bps:Math.round(Number(f.get("min_risk"))*100),max_at_risk_bps:Math.round(Number(f.get("max_risk"))*100),commitment_ttl_minutes:1440})});toast("Seller intent published.");await refresh()}catch(err){toast(err.message,true)}}
async function seed(){try{await api("/api/carbon/demo/seed",{method:"POST",actor:false});await refresh();toast("Demo market loaded. No money moved.")}catch(err){toast(err.message,true)}}
async function refresh(){try{const results=await Promise.all([api("/api/carbon/bootstrap",{actor:false}),api("/api/carbon/me")]);const boot=results[0];S.me=results[1];S.listings=boot.listings||[];$("#mode").textContent=boot.demo_mode?"Sandbox · no money moved":"Writes fail closed";$("#seed").disabled=!boot.demo_mode;render()}catch(err){$("#mode").textContent="Disconnected";toast(err.message,true)}}

$$(".nav").forEach(b=>b.onclick=()=>setView(b.dataset.view));
$$(".filter").forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;$$(".filter").forEach(x=>x.classList.toggle("active",x===b));renderMarket()});
$("#persona").onclick=cyclePersona;$("#seed").onclick=seed;$("#listingForm").onsubmit=createListing;$("#bondAmount").oninput=syncBond;$("#riskAmount").oninput=syncBond;$("#bondForm").onsubmit=submitBond;$("#interestClose").onclick=()=>$("#interestDialog").close();$("#interestBondFilter").oninput=renderInterestCandidates;$("#interestRiskFilter").oninput=renderInterestCandidates;$("#interestTodayFilter").onchange=renderInterestCandidates;$("#messageClose").onclick=()=>$("#messageDialog").close();$("#messageForm").onsubmit=sendMessage;$("#extensionForm").onsubmit=submitExtension;$("#intent").oninput=renderMarket;
$$("input[name=min_risk],input[name=max_risk]").forEach(i=>i.oninput=()=>i.parentElement.querySelector("output").value=i.value+"%");
refresh();
})();