(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const P={browser:{label:"Browser",actor:"carbon-demo-browser-2026"},buyer:{label:"Buyer",actor:"carbon-demo-buyer-2026"},seller:{label:"Seller",actor:"carbon-demo-seller-2026"}};
const THEMES={
  carbon:{buyer:"#E8FF5C",seller:"#FF7A3D"},
  ice:{buyer:"#69D8FF",seller:"#FF8257"},
  orchid:{buyer:"#BC8CFF",seller:"#F2C85A"},
  cobalt:{buyer:"#4B86FF",seller:"#FF668E"},
  teal:{buyer:"#40D5C1",seller:"#FF8069"},
  pearl:{buyer:"#E7E0D2",seller:"#C78A59"},
  matrix:{buyer:"#00FF72",seller:"#D7FF00",premium:true}
};
const savedTheme=JSON.parse(localStorage.getItem("carbon-role-theme")||'{"name":"carbon"}');
const S={persona:"browser",filter:"ALL",query:"",listings:[],me:null,activeListing:null,activeInterest:null,activeCommitment:null,interestRecords:[],interestListing:null,uploadedImages:[],autoSeeding:false,theme:savedTheme,profileAvatarDraft:"",matrixPreviewTimer:null,preference:JSON.parse(localStorage.getItem("carbon-market-preference")||'{"PATIENT":0,"OPEN":0,"MOTIVATED":0,"URGENT":0}')};
const money=(n,c="ZAR")=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:c,maximumFractionDigits:0}).format((n||0)/100);
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
function applyUIScale(value,persist=true){const v=clamp(Number(value)||100,85,125);document.documentElement.style.setProperty("--ui-scale",String(v/100));const slider=$("#uiScale");if(slider)slider.value=String(v);if(persist)localStorage.setItem("carbon-ui-scale",String(v));requestAnimationFrame(updateWheelDepth)}
function initUIScale(){const stored=Number(localStorage.getItem("carbon-ui-scale")||100);applyUIScale(stored,false);const slider=$("#uiScale");if(slider)slider.oninput=()=>applyUIScale(slider.value);if($("#sizeDown"))$("#sizeDown").onclick=()=>applyUIScale((Number(slider.value)||100)-5);if($("#sizeUp"))$("#sizeUp").onclick=()=>applyUIScale((Number(slider.value)||100)+5)}
function learnPreference(listing,weight=.2){if(!listing)return;const key=listing.seller_intent||"OPEN";S.preference[key]=clamp(Number(S.preference[key]||0)+weight,-2,4);localStorage.setItem("carbon-market-preference",JSON.stringify(S.preference))}
function themePair(){if(S.theme&&S.theme.name==="custom")return{buyer:S.theme.buyer||"#69D8FF",seller:S.theme.seller||"#FF8257"};return THEMES[(S.theme&&S.theme.name)||"carbon"]||THEMES.carbon}
function applyRoleTheme(){const pair=themePair();document.documentElement.style.setProperty("--buyer",pair.buyer);document.documentElement.style.setProperty("--seller",pair.seller);document.body.dataset.role=S.persona;$(".themeChoice").forEach(x=>x.classList.toggle("active",x.dataset.theme===S.theme.name));const dots=$(".themeDots i");if(dots[0])dots[0].style.background=pair.buyer;if(dots[1])dots[1].style.background=pair.seller}
function saveTheme(name,buyer,seller){S.theme=name==="custom"?{name,buyer,seller}:{name};localStorage.setItem("carbon-role-theme",JSON.stringify(S.theme));document.body.classList.remove("matrixPreview");applyRoleTheme();toast(name==="custom"?"Custom role pair applied.":(name==="matrix"?"Matrix° entitlement required.":"Role palette applied."))}
function openTheme(){applyRoleTheme();$("#themeDialog").showModal()}
function previewMatrix(){clearTimeout(S.matrixPreviewTimer);document.body.classList.add("matrixPreview");S.matrixPreviewTimer=setTimeout(()=>document.body.classList.remove("matrixPreview"),12000);toast("Matrix° premium preview · 12 seconds")}
function profileAvatarMarkup(url,label){return url?'<img src="'+esc(url)+'" alt="'+esc(label||"Profile thumbnail")+'">':'C°'}
function renderProfile(){if(!S.me)return;const p=S.me.profile||{},sum=S.me.summary||{};$("#profileName").textContent=p.display_name||"Participant";$("#profileRef").textContent=S.me.actor_ref||"C°…";$("#displayName").value=p.display_name||"";$("#profileAvatar").innerHTML=profileAvatarMarkup(p.avatar_url,p.display_name);$("#avatarMini").innerHTML=profileAvatarMarkup(p.avatar_url,p.display_name);const values=[["honoured",sum.honoured_commitments||0],["active",sum.active_commitments||0],["valid exits",sum.valid_exits||0],["review",sum.review_states||0],["bonded deals",sum.bonded_deals||0],["actions",sum.recorded_actions||0]];$("#profileMetrics").innerHTML=values.map(([k,v])=>'<div class="profileMetric"><b>'+v+'</b><span>'+k+'</span></div>').join("")}
async function openProfile(){renderProfile();$("#profileDialog").showModal()}
async function saveProfile(){try{let avatar=(S.me&&S.me.profile&&S.me.profile.avatar_url)||"";const file=$("#avatarInput").files&&$("#avatarInput").files[0];if(file){avatar=(await uploadFiles([file],512,.84))[0]||avatar}S.me=await api("/api/carbon/me/profile",{method:"POST",body:JSON.stringify({display_name:$("#displayName").value,avatar_url:avatar})});renderProfile();toast("Profile updated.")}catch(err){toast(err.message,true)}}
function toast(message,bad=false){const el=$("#toast");el.textContent=message;el.classList.toggle("bad",bad);el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
async function api(path,opt={}){const options={...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}};if(opt.actor!==false)options.headers["X-CARBON-Actor"]=P[S.persona].actor;const response=await fetch(path,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||("Request failed "+response.status));return data}
function esc(value=""){const d=document.createElement("div");d.textContent=value;return d.innerHTML}
function setView(name){$$(".view").forEach(x=>x.classList.toggle("activeView",x.id===name));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===name));if(name==="sell")renderSeller();if(name==="activity")renderActivity()}
async function cyclePersona(){const order=["browser","buyer","seller"];S.persona=order[(order.indexOf(S.persona)+1)%3];$("#personaLabel").textContent=P[S.persona].label;applyRoleTheme();await refresh();toast("Now acting as "+P[S.persona].label);if(S.persona==="seller")setView("sell")}
function intentScore(x){const posture={PATIENT:1,OPEN:2,MOTIVATED:3,URGENT:4}[x.seller_intent]||1;return posture*10+x.market.bonded*2+x.market.qualified*3+x.market.active_commitments*5}
function adaptiveScore(x){const posture={PATIENT:1,OPEN:2,MOTIVATED:3,URGENT:4}[x.seller_intent]||1;const intent=Number($("#intent").value||18)/100;const market=(x.market.bonded||0)*3+(x.market.qualified||0)*4+(x.market.active_commitments||0)*7;const preference=Number(S.preference[x.seller_intent]||0)*8;return posture*(3+intent*6)+market*(.4+intent*.8)+preference}
function visibleListings(){const q=(S.query||"").trim().toLowerCase();let list=S.listings.filter(x=>(S.filter==="ALL"||x.seller_intent===S.filter)&&(!q||[x.title,x.description,x.seller_intent,x.negotiability].some(v=>String(v||"").toLowerCase().includes(q))));return [...list].sort((a,b)=>adaptiveScore(b)-adaptiveScore(a))}
function render(){renderMarket();renderSeller();renderActivity()}
function evidenceText(e,label){if(!e||e.evidence_state==="UNKNOWN")return label+" evidence: unknown — not bad.";return label+" evidence: "+e.honoured+" honoured · "+e.bonded_deals+" bonded deals · "+e.valid_exits+" valid exits · "+e.review_states+" review states."}
function renderMarket(){const list=visibleListings();$("#emptyMarket").classList.toggle("hidden",list.length>0);$("#grid").innerHTML=list.map((x,i)=>card(x,i)).join("");const totals=S.listings.reduce((a,x)=>{a.bonded+=x.market.bonded;a.qualified+=x.market.qualified;a.active+=x.market.active_commitments;return a},{bonded:0,qualified:0,active:0});$("#stats").innerHTML='<span class="stat"><b>'+S.listings.length+'</b> listings</span><span class="stat"><b>'+totals.bonded+'</b> bonded</span><span class="stat"><b>'+totals.qualified+'</b> qualified</span><span class="stat"><b>'+totals.active+'</b> active</span>';$$("[data-bond]").forEach(b=>b.onclick=()=>{const x=S.listings.find(y=>y.id===b.dataset.bond);learnPreference(x,.35);openBond(b.dataset.bond)});$$("[data-interest]").forEach(b=>b.onclick=()=>openInterests(b.dataset.interest));$(".card").forEach(el=>{el.onpointermove=e=>{const r=el.getBoundingClientRect();el.style.setProperty("--mx",((e.clientX-r.left)/r.width*100).toFixed(1)+"%");el.style.setProperty("--my",((e.clientY-r.top)/r.height*100).toFixed(1)+"%")}});$(".cardMedia").forEach((el,i)=>{el.onclick=()=>openGallery(list[i])});requestAnimationFrame(updateWheelDepth)}
function card(x,i=0){const mine=Boolean(S.me&&S.me.actor_ref===x.seller_ref);let action='<button class="button primary" data-bond="'+x.id+'">Show intent</button>';if(S.persona==="seller"&&mine)action='<button class="button" data-interest="'+x.id+'">Qualified interest</button>';if(S.persona==="seller"&&!mine)action='<span class="pill">Another seller\'s listing</span>';const images=x.image_urls||[],sp=x.seller_profile||{};const media=images.length?'<div class="cardMedia"><img src="'+esc(images[0])+'" alt="'+esc(x.title)+'" loading="lazy"><span class="mediaCount">'+images.length+' image'+(images.length===1?'':'s')+'</span></div>':'<div class="cardMedia"></div>';const sellerAvatar=sp.avatar_url?'<img src="'+esc(sp.avatar_url)+'" alt="">':'C°';const seller='<div class="sellerMeta"><span class="sellerAvatar">'+sellerAvatar+'</span><span><b>'+esc(sp.display_name||"Verified participant")+'</b><small>'+esc(x.seller_ref)+'</small></span></div>';return '<article class="card" style="--card-i:'+i+'"><span class="cardGlow"></span>'+media+'<div class="cardTop"><span class="state">'+x.seller_intent+'</span><span class="muted">'+x.negotiability+'</span></div>'+seller+'<h3>'+esc(x.title)+'</h3><div class="price">'+money(x.price_minor,x.currency)+'</div><p>'+esc(x.description||"")+'</p><p class="muted">'+(x.min_bond_minor===0?'Open access · no bond required. Voluntary commitment up to '+money(x.max_considered_bond_minor,x.currency)+'.':'Minimum bond '+money(x.min_bond_minor,x.currency)+' · maximum meaningful commitment '+money(x.max_considered_bond_minor,x.currency)+'.')+'</p><p class="muted">'+esc(evidenceText(x.seller_evidence,"Seller"))+'</p><div class="signals"><div class="signal"><b>'+x.market.bonded+'</b><span>bonded</span></div><div class="signal"><b>'+x.market.qualified+'</b><span>qualified</span></div><div class="signal"><b>'+x.market.active_commitments+'</b><span>active</span></div></div><div class="actions">'+action+'</div></article>'}
function renderSeller(){const el=$("#sellerListings");if(S.persona!=="seller"){el.innerHTML='<div class="empty"><b>Seller controls stay with the seller.</b><span>Switch to Seller to publish or select.</span></div>';return}const owned=(S.me&&S.me.listings)||[];el.innerHTML=owned.length?owned.map(raw=>{const x=S.listings.find(l=>l.id===raw.id)||raw;const market=x.market||{bonded:0,qualified:0};return '<div class="row"><div class="rowMain"><strong>'+esc(x.title)+'</strong><span>'+x.seller_intent+' · '+money(x.min_bond_minor,x.currency)+' minimum · '+market.bonded+' bonded</span></div><button class="button" data-interest="'+x.id+'">Review</button></div>'}).join(""):'<div class="empty"><b>No seller listings yet.</b><span>Publish only when you actually want to sell.</span></div>';$$("[data-interest]",el).forEach(b=>b.onclick=()=>openInterests(b.dataset.interest))}
function activityRows(){if(!S.me)return[];const rows=[];(S.me.interests||[]).forEach(r=>rows.push({kind:"interest",record:r,updated:r.updated_at}));(S.me.commitments||[]).forEach(r=>rows.push({kind:"commitment",record:r,updated:r.updated_at}));(S.me.deals||[]).forEach(r=>rows.push({kind:"deal",record:r,updated:r.updated_at}));(S.me.extensions||[]).forEach(r=>rows.push({kind:"extension",record:r,updated:r.updated_at}));return rows.sort((a,b)=>String(b.updated).localeCompare(String(a.updated)))}
function activityButtons(item){const r=item.record,me=S.me&&S.me.actor_ref;if(item.kind==="commitment"){const terms='<button class="button" data-action="terms" data-id="'+r.id+'">Terms</button>';if(r.state==="SELECTED"&&r.buyer_ref===me)return '<button class="button primary" data-action="terms" data-id="'+r.id+'">Review & confirm</button><button class="button" data-action="cancel" data-id="'+r.id+'">Exit</button>';if(r.state==="SELECTED"&&r.seller_ref===me)return terms+'<button class="button" data-action="cancel" data-id="'+r.id+'">Release</button>';if(r.state==="ACTIVE_COMMITMENT"){const already=(r.buyer_ref===me&&r.buyer_performed)||(r.seller_ref===me&&r.seller_performed);return terms+(already?'<span class="pill">Performance recorded</span>':'<button class="button primary" data-action="perform" data-id="'+r.id+'">Confirm performance</button>')+'<button class="button" data-action="extend" data-id="'+r.id+'">Extend</button><button class="button" data-action="cancel" data-id="'+r.id+'">Exit</button>'}if(r.state==="HONOURED")return terms+'<button class="button primary" data-action="deal" data-id="'+r.id+'">Inspect / deal</button>'}if(item.kind==="extension"&&r.status==="PENDING"){const com=(S.me&&S.me.commitments||[]).find(x=>x.id===r.commitment_id);if(com&&r.requester_ref!==me)return '<button class="button primary" data-action="extension-accept" data-id="'+r.id+'">Accept change</button><button class="button" data-action="extension-reject" data-id="'+r.id+'">Reject</button>';return '<span class="pill">Waiting for response</span>'}if(item.kind==="deal"&&r.state==="FUNDING_REQUIRED"){if(r.buyer_ref===me)return '<button class="button primary" data-action="fund" data-id="'+r.id+'">Secure purchase funds</button><button class="button" data-action="decline" data-id="'+r.id+'">No deal</button>';return '<span class="pill">Waiting for purchase funds</span><button class="button" data-action="decline" data-id="'+r.id+'">No deal</button>'}if(item.kind==="deal"&&r.state==="INSPECTION"){const accepted=(r.buyer_ref===me&&r.buyer_accept)||(r.seller_ref===me&&r.seller_accept);return (accepted?'<span class="pill">Your acceptance recorded</span>':'<button class="button primary" data-action="accept" data-id="'+r.id+'">Accept deal</button>')+'<button class="button" data-action="decline" data-id="'+r.id+'">No deal</button>'}return ""}
function activityNote(item){const r=item.record;if(item.kind==="interest"){if(r.state==="BONDED_INTEREST")return "Waiting for seller selection. No breach consequence is active.";if(r.state==="QUALIFIED_INTEREST")return "Seller allows open access. No money is bonded and no breach consequence is active.";if(r.state.includes("RELEASE"))return r.provider_ref==="NO_BOND_REQUIRED"?"Interest expired or closed. No money was held.":"Liquidity is marked for release.";return "Buyer intent evidence."}if(item.kind==="commitment"){if(r.state==="SELECTED")return "Seller selected. Buyer must confirm before consequence activates.";if(r.state==="ACTIVE_COMMITMENT")return "Bilateral commitment is active until "+new Date(r.end_at).toLocaleString()+".";if(r.state==="PERFORMANCE_REVIEW")return "Time window ended. CARBON° did not infer who was at fault.";if(r.state==="HONOURED")return "Both parties confirmed performance.";return r.resolution||"Commitment evidence."}if(item.kind==="extension"){if(r.status==="PENDING")return "Requested change. Original commitment remains in force until accepted.";if(r.status==="ACCEPTED")return "Both parties accepted the new time window.";return "Extension was not accepted; original commitment remained in force."}if(item.kind==="deal"){if(r.state==="FUNDING_REQUIRED")return "The appointment was honoured. Bond money stays separate; the buyer must now secure the full purchase amount before acceptance.";if(r.state==="INSPECTION")return "Purchase funds are secured. Inspect the item; both sides retain their own acceptance decision.";if(r.state==="BONDED_DEAL")return "Both accepted. Settlement is ready for a regulated provider.";if(r.state==="NO_DEAL")return "Inspection ended without a purchase. The honoured commitment can release.";return r.settlement_state||"Deal evidence."}return ""}
function messageInterestId(item){if(item.kind==="interest")return item.record.id;if(item.kind==="commitment")return item.record.interest_id;if(item.kind==="extension"){const c=(S.me&&S.me.commitments||[]).find(x=>x.id===item.record.commitment_id);return c&&c.interest_id}if(item.kind==="deal"){const c=(S.me&&S.me.commitments||[]).find(x=>x.id===item.record.commitment_id);return c&&c.interest_id}return null}
function renderActivity(){const rows=activityRows(),el=$("#activityList");$("#emptyActivity").classList.toggle("hidden",rows.length>0);el.innerHTML=rows.map(item=>{const r=item.record,id=messageInterestId(item);const msg=id?'<button class="button" data-message="'+id+'">Message</button>':"";return '<div class="row"><div class="rowMain"><span class="state">'+esc(r.state||item.kind)+'</span><strong>'+esc(r.id)+'</strong><span>'+esc(activityNote(item))+'</span></div><div class="actions">'+msg+activityButtons(item)+'</div></div>'}).join("");$$("[data-action]",el).forEach(b=>b.onclick=()=>activityAction(b.dataset.action,b.dataset.id));$$("[data-message]",el).forEach(b=>b.onclick=()=>openMessages(b.dataset.message))}
function parseTerms(record){try{return JSON.parse(record.terms_json||"{}")}catch(_){return {}}}
function openTerms(id){const r=(S.me&&S.me.commitments||[]).find(x=>x.id===id);if(!r){toast("Commitment not found.",true);return}S.activeCommitment=id;const t=parseTerms(r),item=t.item||{},windowTerm=t.window||{},buyer=t.buyer||{},seller=t.seller||{};$("#termsBody").innerHTML='<div class="panel"><b>'+esc(item.title||"Committed item")+'</b><p>'+esc(item.description||"")+'</p><p><strong>'+money(item.price_minor||0,item.currency||"ZAR")+'</strong></p></div><div class="twocol"><div class="note"><b>Buyer</b><span>Attend or exit through CARBON°. Bond '+money(buyer.bond_minor||0,item.currency||"ZAR")+' · '+money(buyer.at_risk_minor||0,item.currency||"ZAR")+' at risk after activation.</span></div><div class="note"><b>Seller</b><span>Reserve the opportunity, hold listed price/terms, attend or exit through CARBON°, and present the item materially as listed.</span></div></div><div class="note"><b>Time</b><span>'+esc(windowTerm.start_at?new Date(windowTerm.start_at).toLocaleString():"—")+' → '+esc(windowTerm.end_at?new Date(windowTerm.end_at).toLocaleString():"—")+'</span></div><p class="micro">Terms hash: '+esc(r.terms_hash||"unavailable")+'</p>';const canConfirm=r.state==="SELECTED"&&r.buyer_ref===(S.me&&S.me.actor_ref);$("#termsConfirm").classList.toggle("hidden",!canConfirm);$("#termsDialog").showModal()}
async function confirmTerms(){if(!S.activeCommitment)return;try{await api("/api/carbon/commitments/"+S.activeCommitment+"/confirm",{method:"POST"});$("#termsDialog").close();toast("Bilateral commitment activated.");await refresh()}catch(err){toast(err.message,true)}}
async function activityAction(action,id){try{let out;if(action==="terms"){openTerms(id);return}if(action==="confirm")out=await api("/api/carbon/commitments/"+id+"/confirm",{method:"POST"});if(action==="perform")out=await api("/api/carbon/commitments/"+id+"/perform",{method:"POST"});if(action==="deal")out=await api("/api/carbon/commitments/"+id+"/deal",{method:"POST"});if(action==="fund")out=await api("/api/carbon/deals/"+id+"/fund",{method:"POST"});if(action==="accept")out=await api("/api/carbon/deals/"+id+"/accept",{method:"POST"});if(action==="extend"){openExtension(id);return}if(action==="extension-accept")out=await api("/api/carbon/extensions/"+id+"/respond",{method:"POST",body:JSON.stringify({action:"ACCEPT"})});if(action==="extension-reject")out=await api("/api/carbon/extensions/"+id+"/respond",{method:"POST",body:JSON.stringify({action:"REJECT"})});if(action==="decline"){const reason=prompt("Why is there no deal? (optional):","")||"";out=await api("/api/carbon/deals/"+id+"/decline",{method:"POST",body:JSON.stringify({reason})})}if(action==="cancel"){const reason=prompt("Reason for exit (optional):","")||"";out=await api("/api/carbon/commitments/"+id+"/cancel",{method:"POST",body:JSON.stringify({reason})})}if(!out)return;toast("State recorded.");await refresh()}catch(e){toast(e.message,true)}}
function openBond(id){if(S.persona==="browser"){S.persona="buyer";$("#personaLabel").textContent=P.buyer.label;applyRoleTheme()}if(S.persona!=="buyer"){toast("Switch to Buyer first.",true);return}const x=S.listings.find(y=>y.id===id);if(!x)return;if(S.me&&S.me.actor_ref===x.seller_ref){toast("You cannot bond your own listing.",true);return}S.activeListing=x;$("#bondTitle").textContent=x.title;$("#bondRules").textContent=x.min_bond_minor===0?"Seller allows open access. You can commit R0 or voluntarily bond up to "+money(x.max_considered_bond_minor,x.currency)+".":"Seller requires at least "+money(x.min_bond_minor,x.currency)+". CARBON° will not accept more than "+money(x.max_considered_bond_minor,x.currency)+" for this commitment.";const amount=$("#bondAmount");amount.min=Math.max(0,Math.round(x.min_bond_minor/100));amount.max=Math.max(Number(amount.min),Math.round(x.max_considered_bond_minor/100));amount.value=amount.min;const risk=$("#riskAmount");risk.min=Math.round(x.min_at_risk_bps/100);risk.max=Math.round(x.max_at_risk_bps/100);risk.value=risk.min;const d=new Date(Date.now()+90*60000);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$("#meeting").value=d.toISOString().slice(0,16);syncBond();$("#bondDialog").showModal()}
function syncBond(){$("#bondOut").textContent="R"+Number($("#bondAmount").value).toLocaleString("en-ZA");$("#riskOut").textContent=$("#riskAmount").value+"%"}
async function submitBond(e){e.preventDefault();const x=S.activeListing;if(!x)return;try{const local=new Date($("#meeting").value);await api("/api/carbon/listings/"+x.id+"/interests",{method:"POST",body:JSON.stringify({bond_minor:Math.round(Number($("#bondAmount").value)*100),at_risk_bps:Math.round(Number($("#riskAmount").value)*100),proposed_start_at:local.toISOString(),proposed_duration_minutes:Number($("#duration").value)})});$("#bondDialog").close();toast("Intent registered. No priority purchased.");await refresh();setView("activity")}catch(err){toast(err.message,true)}}
function renderInterestCandidates(){const x=S.interestListing;if(!x)return;const minBond=Number($("#interestBondFilter").value)*100,minRisk=Number($("#interestRiskFilter").value)*100,today=$("#interestTodayFilter").checked;$("#interestBondOut").textContent="R"+Number($("#interestBondFilter").value).toLocaleString("en-ZA");$("#interestRiskOut").textContent=$("#interestRiskFilter").value+"%";const now=new Date();const records=S.interestRecords.filter(i=>i.considered_bond_minor>=minBond&&i.at_risk_bps>=minRisk&&(!today||new Date(i.proposed_start_at).toDateString()===now.toDateString()));$("#interestList").innerHTML=records.length?records.map(i=>{const bp=i.buyer_profile||{},avatar=bp.avatar_url?'<img src="'+esc(bp.avatar_url)+'" alt="">':'C°';return '<div class="row"><div class="buyerIdentity"><span class="sellerAvatar">'+avatar+'</span></div><div class="rowMain"><span class="state">'+i.state+'</span><strong>'+esc(bp.display_name||"Qualified participant")+' · '+money(i.considered_bond_minor,x.currency)+' committed</strong><span>'+Math.round(i.at_risk_bps/100)+'% proposed at risk · '+new Date(i.proposed_start_at).toLocaleString()+'</span><span>'+esc(evidenceText(i.buyer_evidence,"Buyer"))+'</span></div><div class="actions"><button class="button" data-message="'+i.id+'">Message</button>'+(["BONDED_INTEREST","QUALIFIED_INTEREST"].includes(i.state)?'<button class="button primary" data-select="'+i.id+'">Select</button>':'')+'</div></div>'}).join(""):'<div class="empty"><b>No buyers match these filters.</b><span>Move the sliders; nobody is penalized for falling outside your current view.</span></div>';$$$("[data-select]",$("#interestList")).forEach(b=>b.onclick=()=>selectInterest(b.dataset.select));$$$("[data-message]",$("#interestList")).forEach(b=>b.onclick=()=>openMessages(b.dataset.message))}
async function openInterests(id){if(S.persona!=="seller"){toast("Seller credential required.",true);return}const x=S.listings.find(y=>y.id===id);if(!x||!S.me||S.me.actor_ref!==x.seller_ref){toast("Only this listing's seller can review qualified interest.",true);return}try{const data=await api("/api/carbon/listings/"+id+"/interests");S.interestRecords=data.records;S.interestListing=x;$("#interestTitle").textContent=x.title;const b=$("#interestBondFilter"),r=$("#interestRiskFilter");b.min=Math.round(x.min_bond_minor/100);b.max=Math.round(x.max_considered_bond_minor/100);b.value=b.min;r.min=Math.round(x.min_at_risk_bps/100);r.max=Math.round(x.max_at_risk_bps/100);r.value=r.min;$("#interestTodayFilter").checked=false;renderInterestCandidates();$("#interestDialog").showModal()}catch(err){toast(err.message,true)}}
async function selectInterest(id){try{await api("/api/carbon/interests/"+id+"/select",{method:"POST",body:JSON.stringify({cancellation_buffer_minutes:120})});$("#interestDialog").close();toast("Selected. Buyer consequence remains inactive.");await refresh();setView("activity")}catch(err){toast(err.message,true)}}
async function compressImage(file,maxEdge=1600,quality=.82){if(!file.type.startsWith("image/"))return file;const bitmap=await createImageBitmap(file);const scale=Math.min(1,maxEdge/Math.max(bitmap.width,bitmap.height));const w=Math.max(1,Math.round(bitmap.width*scale)),h=Math.max(1,Math.round(bitmap.height*scale));const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.getContext("2d",{alpha:false}).drawImage(bitmap,0,0,w,h);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/webp",quality));return blob&&blob.size<file.size?new File([blob],file.name.replace(/\.[^.]+$/,"")+".webp",{type:"image/webp"}):file}
async function uploadFiles(files,maxEdge=1600,quality=.82){const prepared=[];for(const file of files)prepared.push(await compressImage(file,maxEdge,quality));const fd=new FormData();prepared.forEach(file=>fd.append("files",file));const response=await fetch("/api/carbon/media",{method:"POST",headers:{"X-CARBON-Actor":P[S.persona].actor},body:fd});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||"Image upload failed");return data.urls||[]}
async function uploadListingImages(){const input=$("#listingImages");if(!input||!input.files.length)return[];return uploadFiles([...input.files].slice(0,6),1600,.82)}
async function createListing(e){e.preventDefault();if(S.persona!=="seller"){toast("Switch to Seller first.",true);return}const f=new FormData(e.currentTarget);try{const image_urls=await uploadListingImages();await api("/api/carbon/listings",{method:"POST",body:JSON.stringify({title:f.get("title"),description:f.get("description"),image_urls,price_minor:Math.round(Number(f.get("price"))*100),currency:"ZAR",seller_intent:f.get("seller_intent"),negotiability:f.get("negotiability"),min_bond_minor:Math.round(Number(f.get("min_bond"))*100),max_considered_bond_minor:Math.round(Number(f.get("max_bond"))*100),min_at_risk_bps:Math.round(Number(f.get("min_risk"))*100),max_at_risk_bps:Math.round(Number(f.get("max_risk"))*100),commitment_ttl_minutes:1440})});toast("Seller intent published.");e.currentTarget.reset();$("#imagePreview").innerHTML="";await refresh()}catch(err){toast(err.message,true)}}
function openGallery(listing){const images=(listing&&listing.image_urls)||[];if(!images.length)return;$("#galleryTitle").textContent=listing.title;const main=$("#galleryMain"),thumbs=$("#galleryThumbs");function select(index){main.src=images[index];main.alt=listing.title+" image "+(index+1);$("button",thumbs).forEach((b,i)=>b.classList.toggle("active",i===index))}thumbs.innerHTML=images.map((url,i)=>'<button type="button" aria-label="View image '+(i+1)+'"><img src="'+esc(url)+'" alt=""></button>').join("");$("button",thumbs).forEach((b,i)=>b.onclick=()=>select(i));select(0);$("#galleryDialog").showModal()}
async function seed(){try{await api("/api/carbon/demo/seed",{method:"POST",actor:false});await refresh();toast("Demo market loaded. No money moved.")}catch(err){toast(err.message,true)}}
async function refresh(){try{const results=await Promise.all([api("/api/carbon/bootstrap",{actor:false}),api("/api/carbon/me")]);const boot=results[0];S.me=results[1];S.listings=boot.listings||[];$("#mode").textContent=boot.demo_mode?"Sandbox · no money moved":"Writes fail closed";$("#seed").disabled=!boot.demo_mode;if(boot.demo_mode&&!sessionStorage.getItem("carbon-demo-seeded")&&!S.autoSeeding){S.autoSeeding=true;try{await api("/api/carbon/demo/seed",{method:"POST",actor:false});sessionStorage.setItem("carbon-demo-seeded","1");S.autoSeeding=false;return refresh()}catch(_){S.autoSeeding=false}}renderProfile();render()}catch(err){$("#mode").textContent="Disconnected";toast(err.message,true)}}

$$(".nav").forEach(b=>b.onclick=()=>setView(b.dataset.view));
$$(".filter").forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;$$(".filter").forEach(x=>x.classList.toggle("active",x===b));renderMarket()});
$("#persona").onclick=cyclePersona;$("#seed").onclick=seed;$("#listingForm").onsubmit=createListing;$("#marketSearch").oninput=e=>{S.query=e.target.value;renderMarket()};$("#galleryClose").onclick=()=>$("#galleryDialog").close();$("#bondAmount").oninput=syncBond;$("#riskAmount").oninput=syncBond;$("#bondForm").onsubmit=submitBond;$("#interestClose").onclick=()=>$("#interestDialog").close();$("#interestBondFilter").oninput=renderInterestCandidates;$("#interestRiskFilter").oninput=renderInterestCandidates;$("#interestTodayFilter").onchange=renderInterestCandidates;$("#messageClose").onclick=()=>$("#messageDialog").close();$("#termsClose").onclick=()=>$("#termsDialog").close();$("#termsConfirm").onclick=confirmTerms;$("#messageForm").onsubmit=sendMessage;$("#extensionClose").onclick=()=>$("#extensionDialog").close();$("#extensionForm").onsubmit=submitExtension;$("#intent").oninput=renderMarket;
$$("input[name=min_risk],input[name=max_risk]").forEach(i=>i.oninput=()=>i.parentElement.querySelector("output").value=i.value+"%");
function previewImages(){const input=$("#listingImages"),out=$("#imagePreview");if(!input||!out)return;out.innerHTML="";[...input.files].slice(0,6).forEach(file=>{const img=document.createElement("img");img.src=URL.createObjectURL(file);img.onload=()=>URL.revokeObjectURL(img.src);out.appendChild(img)})}
function updateWheelDepth(){const rail=$("#grid");if(!rail)return;const box=rail.getBoundingClientRect(),center=box.left+box.width/2;$$(".card",rail).forEach(card=>{const r=card.getBoundingClientRect(),d=clamp(((r.left+r.width/2)-center)/(Math.max(1,box.width)*.48),-1,1),a=Math.abs(d);card.style.setProperty("--wheel-tilt",(d*-12).toFixed(2)+"deg");card.style.setProperty("--wheel-lift",(a*8).toFixed(1)+"px");card.style.setProperty("--wheel-depth",((1-a)*24).toFixed(1)+"px");card.style.setProperty("--wheel-scale",(1-a*.055).toFixed(3));card.style.setProperty("--wheel-opacity",(1-a*.2).toFixed(3));card.dataset.wheelCenter=a<.18?"true":"false"})}
function initMarketRail(){const rail=$("#grid");if(!rail)return;$("#railPrev").onclick=()=>rail.scrollBy({left:-Math.max(280,rail.clientWidth*.68),behavior:"smooth"});$("#railNext").onclick=()=>rail.scrollBy({left:Math.max(280,rail.clientWidth*.68),behavior:"smooth"});rail.addEventListener("scroll",()=>requestAnimationFrame(updateWheelDepth),{passive:true});rail.addEventListener("wheel",e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();rail.scrollLeft+=e.deltaY}},{passive:false});let drag=false,startX=0,startScroll=0;rail.addEventListener("pointerdown",e=>{if(e.pointerType==="touch")return;drag=true;startX=e.clientX;startScroll=rail.scrollLeft;rail.classList.add("dragging");rail.setPointerCapture(e.pointerId)});rail.addEventListener("pointermove",e=>{if(drag)rail.scrollLeft=startScroll-(e.clientX-startX)});const end=()=>{drag=false;rail.classList.remove("dragging");requestAnimationFrame(updateWheelDepth)};rail.addEventListener("pointerup",end);rail.addEventListener("pointercancel",end);window.addEventListener("resize",()=>requestAnimationFrame(updateWheelDepth),{passive:true})}
function initMatrixRain(){const canvas=$("#matrixRain");if(!canvas)return;const ctx=canvas.getContext("2d");let cols=[],w=0,h=0,last=0;function resize(){const d=Math.min(2,devicePixelRatio||1);w=canvas.width=innerWidth*d;h=canvas.height=innerHeight*d;canvas.style.width=innerWidth+"px";canvas.style.height=innerHeight+"px";const count=Math.ceil(w/(18*d));cols=Array.from({length:count},()=>Math.random()*h)}window.addEventListener("resize",resize,{passive:true});resize();function draw(t){if(t-last>48){last=t;ctx.fillStyle="rgba(2,7,4,.08)";ctx.fillRect(0,0,w,h);ctx.font=(13*(devicePixelRatio||1))+"px IBM Plex Mono, monospace";for(let i=0;i<cols.length;i++){const y=cols[i],x=i*18*(devicePixelRatio||1);ctx.fillStyle=i%7===0?"rgba(215,255,0,.72)":"rgba(0,255,114,.48)";ctx.fillText(String.fromCharCode(0x30A0+Math.random()*96),x,y);cols[i]=y>h+80||Math.random()>.985?0:y+17*(devicePixelRatio||1)}}requestAnimationFrame(draw)}requestAnimationFrame(draw)}
function initCarbonField(){const canvas=$("#carbonField");if(!canvas)return;const gl=canvas.getContext("webgl",{alpha:true,antialias:false});if(!gl){canvas.style.display="none";return}const vs=gl.createShader(gl.VERTEX_SHADER);gl.shaderSource(vs,"attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}");gl.compileShader(vs);const fs=gl.createShader(gl.FRAGMENT_SHADER);gl.shaderSource(fs,"precision mediump float;uniform vec2 r;uniform vec2 m;uniform float t;float ring(vec2 p,float rad,float w){return 1.-smoothstep(0.,w,abs(length(p)-rad));}void main(){vec2 uv=(gl_FragCoord.xy-.5*r)/min(r.x,r.y);vec2 p=uv+(m-.5)*.12;float tt=t*.00022;float a=ring(p,.48+.025*sin(tt),.018)+ring(p+vec2(.18,-.08),.74+.03*cos(tt*.7),.012);float mesh=.5+.5*sin((uv.x+uv.y)*64.+tt)*sin((uv.x-uv.y)*58.-tt*.8);mesh=smoothstep(.92,1.,mesh);vec3 c=vec3(.01)+vec3(.18,.19,.025)*a+vec3(.055)*mesh;float alpha=clamp(a*.75+mesh*.14+.04,0.,.7);gl_FragColor=vec4(c,alpha);}");gl.compileShader(fs);const pr=gl.createProgram();gl.attachShader(pr,vs);gl.attachShader(pr,fs);gl.bindAttribLocation(pr,0,"p");gl.linkProgram(pr);gl.useProgram(pr);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(pr,"r"),um=gl.getUniformLocation(pr,"m"),ut=gl.getUniformLocation(pr,"t");let mx=.5,my=.5;window.addEventListener("pointermove",e=>{mx=e.clientX/innerWidth;my=1-e.clientY/innerHeight},{passive:true});function draw(t){const d=Math.min(2,devicePixelRatio||1),w=Math.max(1,canvas.clientWidth*d|0),h=Math.max(1,canvas.clientHeight*d|0);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}gl.uniform2f(ur,w,h);gl.uniform2f(um,mx,my);gl.uniform1f(ut,t);gl.drawArrays(gl.TRIANGLES,0,3);if(!matchMedia("(prefers-reduced-motion: reduce)").matches)requestAnimationFrame(draw)}requestAnimationFrame(draw)}
if($("#listingImages"))$("#listingImages").onchange=previewImages;
if($("#avatarInput"))$("#avatarInput").onchange=()=>{const file=$("#avatarInput").files&&$("#avatarInput").files[0];if(!file)return;const url=URL.createObjectURL(file);$("#profileAvatar").innerHTML='<img src="'+url+'" alt="Profile thumbnail preview">';setTimeout(()=>URL.revokeObjectURL(url),60000)};
$("#themeButton").onclick=openTheme;$("#themeClose").onclick=()=>$("#themeDialog").close();$("#profileButton").onclick=openProfile;$("#profileClose").onclick=()=>$("#profileDialog").close();$("#saveProfile").onclick=saveProfile;
$$(".themeChoice").forEach(btn=>btn.onclick=()=>{if(btn.dataset.premium==="true"){previewMatrix();return}saveTheme(btn.dataset.theme);$("#themeDialog").close()});
$("#applyCustomTheme").onclick=()=>{saveTheme("custom",$("#customBuyer").value,$("#customSeller").value);$("#themeDialog").close()};
initUIScale();applyRoleTheme();initMarketRail();initCarbonField();initMatrixRain();refresh();
})();