(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const P={browser:{label:"Browser",actor:"carbon-demo-browser-2026"},buyer:{label:"Buyer",actor:"carbon-demo-buyer-2026"},seller:{label:"Seller",actor:"carbon-demo-seller-2026"}};
const S={persona:"browser",filter:"ALL",listings:[],activeListing:null,activity:JSON.parse(localStorage.getItem("carbon-activity")||"[]")};
const money=(n,c="ZAR")=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:c,maximumFractionDigits:0}).format((n||0)/100);
function toast(m,bad=false){const el=$("#toast");el.textContent=m;el.classList.toggle("bad",bad);el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
async function api(path,opt={}){const o={...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}};if(opt.actor!==false)o.headers["X-CARBON-Actor"]=P[S.persona].actor;const r=await fetch(path,o);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||("Request failed "+r.status));return data}
function saveActivity(kind,record,note){S.activity.unshift({kind,record,note,at:new Date().toISOString()});S.activity=S.activity.slice(0,40);localStorage.setItem("carbon-activity",JSON.stringify(S.activity));renderActivity()}
function view(name){$$(".view").forEach(x=>x.classList.toggle("activeView",x.id===name));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===name));if(name==="sell")renderSeller();if(name==="activity")renderActivity()}
function cyclePersona(){const order=["browser","buyer","seller"];S.persona=order[(order.indexOf(S.persona)+1)%3];$("#personaLabel").textContent=P[S.persona].label;toast("Now acting as "+P[S.persona].label);render();if(S.persona==="seller")view("sell")}
function render(){renderMarket();renderSeller();renderActivity()}
function renderMarket(){const list=S.listings.filter(x=>S.filter==="ALL"||x.seller_intent===S.filter);$("#emptyMarket").classList.toggle("hidden",list.length>0);$("#grid").innerHTML=list.map(card).join("");const totals=S.listings.reduce((a,x)=>{a.bonded+=x.market.bonded;a.qualified+=x.market.qualified;a.active+=x.market.active_commitments;return a},{bonded:0,qualified:0,active:0});$("#stats").innerHTML='<span class="stat"><b>'+S.listings.length+'</b> listings</span><span class="stat"><b>'+totals.bonded+'</b> bonded</span><span class="stat"><b>'+totals.qualified+'</b> qualified</span><span class="stat"><b>'+totals.active+'</b> active</span>';$$("[data-bond]").forEach(b=>b.onclick=()=>openBond(b.dataset.bond));$$("[data-interest]").forEach(b=>b.onclick=()=>openInterests(b.dataset.interest))}
function card(x){const seller=S.persona==="seller";return '<article class="card"><div class="cardTop"><span class="state">'+x.seller_intent+'</span><span class="muted">'+x.negotiability+'</span></div><h3>'+esc(x.title)+'</h3><div class="price">'+money(x.price_minor,x.currency)+'</div><p>'+esc(x.description||"")+'</p><p class="muted">Minimum bond '+money(x.min_bond_minor,x.currency)+' · up to '+money(x.max_considered_bond_minor,x.currency)+' counts toward commitment strength.</p><div class="signals"><div class="signal"><b>'+x.market.bonded+'</b><span>bonded</span></div><div class="signal"><b>'+x.market.qualified+'</b><span>qualified</span></div><div class="signal"><b>'+x.market.active_commitments+'</b><span>active</span></div></div><div class="actions">'+(seller?'<button class="button" data-interest="'+x.id+'">Qualified interest</button>':'<button class="button primary" data-bond="'+x.id+'">Show intent</button>')+'</div></article>'}
function renderSeller(){const el=$("#sellerListings");if(S.persona!=="seller"){el.innerHTML='<div class="empty"><b>Seller controls stay with the seller.</b><span>Switch persona to Seller to publish or select.</span></div>';return}el.innerHTML=S.listings.length?S.listings.map(x=>'<div class="row"><div class="rowMain"><strong>'+esc(x.title)+'</strong><span>'+x.seller_intent+' · '+money(x.min_bond_minor,x.currency)+' minimum · '+x.market.bonded+' bonded</span></div><button class="button" data-interest="'+x.id+'">Review</button></div>').join(""):'<div class="empty"><b>No listings.</b></div>';$$("[data-interest]",el).forEach(b=>b.onclick=()=>openInterests(b.dataset.interest))}
function renderActivity(){const el=$("#activityList");$("#emptyActivity").classList.toggle("hidden",S.activity.length>0);el.innerHTML=S.activity.map((a,i)=>{const r=a.record||{};let buttons="";if(a.kind==="commitment"&&r.state==="SELECTED"&&S.persona==="buyer")buttons='<button class="button primary" data-act="confirm" data-i="'+i+'">Confirm commitment</button>';if(a.kind==="commitment"&&r.state==="ACTIVE_COMMITMENT")buttons='<button class="button" data-act="perform" data-i="'+i+'">Confirm performance</button>';if(a.kind==="commitment"&&r.state==="HONOURED")buttons='<button class="button primary" data-act="deal" data-i="'+i+'">Inspect / deal</button>';if(a.kind==="deal"&&r.state==="INSPECTION")buttons='<button class="button primary" data-act="accept" data-i="'+i+'">Accept deal</button>';return '<div class="row"><div class="rowMain"><span class="state">'+esc(r.state||a.kind)+'</span><strong>'+esc(r.id||"activity")+'</strong><span>'+esc(a.note||"")+'</span></div><div>'+buttons+'</div></div>'}).join("");$$("[data-act]",el).forEach(b=>b.onclick=()=>activityAction(b.dataset.act,Number(b.dataset.i)))}
async function activityAction(action,i){const a=S.activity[i],r=a.record;try{let out;if(action==="confirm")out=await api("/api/carbon/commitments/"+r.id+"/confirm",{method:"POST"});if(action==="perform")out=await api("/api/carbon/commitments/"+r.id+"/perform",{method:"POST"});if(action==="deal")out=await api("/api/carbon/commitments/"+r.id+"/deal",{method:"POST"});if(action==="accept")out=await api("/api/carbon/deals/"+r.id+"/accept",{method:"POST"});if(!out)return;S.activity.splice(i,1);saveActivity(action==="deal"||action==="accept"?"deal":"commitment",out.record,action==="accept"?"Acceptance recorded. Settlement remains provider-controlled.":"State advanced.");toast("State advanced.");await refresh()}catch(e){toast(e.message,true)}}
function openBond(id){if(S.persona==="browser")S.persona="buyer",$("#personaLabel").textContent=P.buyer.label;if(S.persona!=="buyer"){toast("Switch to Buyer mode first.",true);return}const x=S.listings.find(y=>y.id===id);if(!x)return;S.activeListing=x;$("#bondTitle").textContent=x.title;$("#bondRules").textContent="Seller requires at least "+money(x.min_bond_minor,x.currency)+". Only up to "+money(x.max_considered_bond_minor,x.currency)+" counts toward commitment strength.";const a=$("#bondAmount");a.min=Math.max(1,Math.round(x.min_bond_minor/100));a.max=Math.max(Number(a.min),Math.round(x.max_considered_bond_minor/100));a.value=Math.round(x.min_bond_minor/100);const rr=$("#riskAmount");rr.min=Math.round(x.min_at_risk_bps/100);rr.max=Math.round(x.max_at_risk_bps/100);rr.value=rr.min;const d=new Date(Date.now()+90*60000);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$("#meeting").value=d.toISOString().slice(0,16);syncBond();$("#bondDialog").showModal()}
function syncBond(){$("#bondOut").textContent="R"+Number($("#bondAmount").value).toLocaleString("en-ZA");$("#riskOut").textContent=$("#riskAmount").value+"%"}
async function submitBond(e){e.preventDefault();const x=S.activeListing;if(!x)return;try{const local=new Date($("#meeting").value);const out=await api("/api/carbon/listings/"+x.id+"/interests",{method:"POST",body:JSON.stringify({bond_minor:Math.round(Number($("#bondAmount").value)*100),at_risk_bps:Math.round(Number($("#riskAmount").value)*100),proposed_start_at:local.toISOString(),proposed_duration_minutes:Number($("#duration").value)})});saveActivity("interest",out.record,"Waiting for seller selection. No consequence is active yet.");$("#bondDialog").close();toast("Intent secured. No priority purchased.");await refresh()}catch(e2){toast(e2.message,true)}}
async function openInterests(id){if(S.persona!=="seller"){toast("Seller credential required.",true);return}try{const data=await api("/api/carbon/listings/"+id+"/interests");const x=S.listings.find(y=>y.id===id);$("#interestTitle").textContent=x?x.title:"Buyer intent";$("#interestList").innerHTML=data.records.length?data.records.map(i=>'<div class="row"><div class="rowMain"><span class="state">'+i.state+'</span><strong>'+money(i.considered_bond_minor,x.currency)+' considered</strong><span>'+money(i.bond_minor,x.currency)+' bonded · '+Math.round(i.at_risk_bps/100)+'% proposed at risk · '+new Date(i.proposed_start_at).toLocaleString()+'</span></div>'+(i.state==="BONDED_INTEREST"?'<button class="button primary" data-select="'+i.id+'">Select</button>':'')+'</div>').join(""):'<div class="empty"><b>No qualified interest.</b><span>Noise does not count as demand.</span></div>';$$("[data-select]",$("#interestList")).forEach(b=>b.onclick=()=>selectInterest(b.dataset.select));$("#interestDialog").showModal()}catch(e){toast(e.message,true)}}
async function selectInterest(id){try{const out=await api("/api/carbon/interests/"+id+"/select",{method:"POST",body:JSON.stringify({cancellation_buffer_minutes:120})});saveActivity("commitment",out.record,"Seller selected. Buyer consequence is still inactive.");$("#interestDialog").close();toast("Selected. Waiting for buyer confirmation.");await refresh()}catch(e){toast(e.message,true)}}
async function createListing(e){e.preventDefault();if(S.persona!=="seller"){toast("Switch to Seller mode first.",true);return}const f=new FormData(e.currentTarget);try{await api("/api/carbon/listings",{method:"POST",body:JSON.stringify({title:f.get("title"),description:f.get("description"),price_minor:Math.round(Number(f.get("price"))*100),currency:"ZAR",seller_intent:f.get("seller_intent"),negotiability:f.get("negotiability"),min_bond_minor:Math.round(Number(f.get("min_bond"))*100),max_considered_bond_minor:Math.round(Number(f.get("max_bond"))*100),min_at_risk_bps:Math.round(Number(f.get("min_risk"))*100),max_at_risk_bps:Math.round(Number(f.get("max_risk"))*100),commitment_ttl_minutes:1440})});toast("Seller intent published.");await refresh()}catch(e2){toast(e2.message,true)}}
async function seed(){try{await api("/api/carbon/demo/seed",{method:"POST",actor:false});await refresh();toast("Demo market loaded. No money moved.")}catch(e){toast(e.message,true)}}
async function refresh(){try{const b=await api("/api/carbon/bootstrap",{actor:false});S.listings=b.listings||[];$("#mode").textContent=b.demo_mode?"Sandbox · no money moved":"Writes fail closed";$("#seed").disabled=!b.demo_mode;render()}catch(e){$("#mode").textContent="Disconnected";toast(e.message,true)}}
function esc(v=""){const d=document.createElement("div");d.textContent=v;return d.innerHTML}
$$(".nav").forEach(b=>b.onclick=()=>view(b.dataset.view));$$(".filter").forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;$$(".filter").forEach(x=>x.classList.toggle("active",x===b));renderMarket()});$("#persona").onclick=cyclePersona;$("#seed").onclick=seed;$("#listingForm").onsubmit=createListing;$("#bondAmount").oninput=syncBond;$("#riskAmount").oninput=syncBond;$("#bondForm").onsubmit=submitBond;$("#interestClose").onclick=()=>$("#interestDialog").close();$$("input[name=min_risk],input[name=max_risk]").forEach(i=>i.oninput=()=>i.parentElement.querySelector("output").value=i.value+"%");refresh();
})();